apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::963938005563:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963938005563:role/eksctl-simple-jwt-app-nodegroup-n-NodeInstanceRole-1XX643FJHN07J
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-09-30T11:47:41Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1955'
  uid: 82eabd49-d955-4813-8e6b-8faa729386af
