apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::963938005563:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963938005563:role/eksctl-simple-flask-app-nodegroup-NodeInstanceRole-PA7OSMB5JPPL
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-09-30T18:38:29Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1432'
  uid: 425fbb7a-1a5c-4255-aac6-65e496861cd8
