apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::963938005563:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963938005563:role/eksctl-simple-jwt-app-nodegroup-n-NodeInstanceRole-1HP8AN3QHH5NG
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: '2022-09-30T16:44:55Z'
  name: aws-auth
  namespace: kube-system
  resourceVersion: '1847'
  uid: 147c5ea7-952d-485c-98a0-f013d514ef0b
